CREATE TABLE t1 ( c INTEGER PRIMARY KEY ON CONFLICT REPLACE , b TEXT , a UNIQUE ) ;
 INSERT INTO t1(b) VALUES(1);
 CREATE TRIGGER c0 AFTER UPDATE  ON t1 BEGIN
     INSERT INTO t1 VALUES(new.c, new.b, new.a)
         ON CONFLICT (a) DO NOTHING;
     END;
 UPDATE t1 SET b = 0;
